let suggestions = [
    "apple",
    "facebook",
    "google",
    "youtube",
    "amazon",
    "instagram",
    "twitter",
    "linkedin",
    "netflix",
    "snapchat",
    "whatsapp",
    "gmail",
    "walmart",
    "ebay",
    "pinterest",
    "microsoft",
    "adobe",
    "yahoo",
    "reddit",
    "tumblr",
    "stackoverflow",
    "github",
    "dropbox",
    "holidays",
    "cricket",
    "football",
    "basketball",
    "tennis",
    "volleyball",
    "hockey",
    "food near me",
    "restaurants near me",
    "hotels near me",
    "amazon prime",
    "google play",
    "maggi",
    "how to make maggi",
    "maggi recipes",
    "maggi restaurants",
    "how to make chocolate cake",
    "chocolate cake recipes",
    "bakery near me",
    "holiday stations to visit",
    "introduction to web development",
    "web development basics",
    "kotlin basics",
    "music",
    "java basics",
    "python basics",
    "javascript basics",
    "c++ basics",
    "c# basics",
    "php basics",
    "kotlin vs java",
    "learn french",
    "news",
    "learn english",
    "node basics",
    "oracle basics",
    "online courses",
    "online c compiler",
    "quora questions",
    "quotes on life",
    "quotes on music",
    "random quotes",
    "react basics",
    "samsung latest mobiles",
    "internships",
    "internet speed",
    "university near me",
    "underwater photography",
    "weather",
    "underwater diving",
    "video games",
    "videography",
    "video editing techniques",
    "xbox",
    "xmas gift ideas",
    "xmas tree decorations",
    "youtube music",
    "yoga tutorials",
    "zoom",
    "zomato",
    "zoo near me",
];